apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: network-test
  name: ovn-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.ovn-deploy
  template:
    metadata:
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: '1'
        ovn.kubernetes.io/logical_switch: ovn-default
      creationTimestamp: null
      labels:
        workload.es.io: deployment.ovn-deploy
        group: network-test
    spec:
      containers:
        - image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: ovn-deploy
      runtimeClassName: rune

