apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: security-setting-test
  name: security-setting-deploy4
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.security-setting-deploy4
  template:
    metadata:
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: '1'
        ovn.kubernetes.io/logical_switch: ovn-default
      creationTimestamp: null
      labels:
        workload.es.io: deployment.security-setting-deploy4
        group: security-setting-test
    spec:
      containers:
        - image: 'hub.ecns.io/library/centos:alltools'
          imagePullPolicy: IfNotPresent
          name: security-setting-deploy4
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 100
            runAsNonRoot: true
            runAsUser: 100
      runtimeClassName: rune
        


        

