apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: command-test
  name: command-deploy2
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.command-deploy2
  template:
    metadata:
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: '1'
        ovn.kubernetes.io/logical_switch: ovn-default
      creationTimestamp: null
      labels:
        workload.es.io: deployment.command-deploy2
        group: command-test
    spec:
      containers:
        - image: 'nginx:latest'
          imagePullPolicy: IfNotPresent
          name: command-deploy2
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - '-c'
                  - echo Running
      runtimeClassName: rune