apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    group: upgrade-strategy-test
  name: upgrade-strategy-dms2
spec:
  selector:
    matchLabels:
      workload.es.io: daemonset.upgrade-strategy-dms2
  template:
    metadata:
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: '1'
        ovn.kubernetes.io/logical_switch: ovn-default
      creationTimestamp: null
      labels:
        workload.es.io: daemonset.upgrade-strategy-dms2
    spec:
      containers:
        - image: 'hub.ecns.io/library/nginx:latest'
          imagePullPolicy: IfNotPresent
          name: upgrade-strategy-dms2
      runtimeClassName: rune
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 300
    type: RollingUpdate