apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: upgrade-strategy-test
  name: upgrade-strategy-deploy6
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.upgrade-strategy-deploy6
  strategy:
    rollingUpdate:
      maxSurge: 300
      maxUnavailable: 300
    type: RollingUpdate
  template:
    metadata:
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: '1'
        ovn.kubernetes.io/logical_switch: ovn-default
      creationTimestamp: null
      labels:
        workload.es.io: deployment.upgrade-strategy-deploy6
        group: upgrade-strategy-test
    spec:
      containers:
        - image: 'hub.ecns.io/library/nginx:latest'
          imagePullPolicy: IfNotPresent
          name: upgrade-strategy-deploy6
      runtimeClassName: rune
        

