apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: statefulset
    workload.es.io/name: httpd
spec:
  selector:
    workload.es.io: statefulset.httpd
  ports:
    - nodePort: 30888
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort