apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    workload.es.io/kind: daemonset
    workload.es.io/name: tomcat-ds
spec:
  selector:
    workload.es.io: daemonset.tomcat
  ports:
    - nodePort: 30889
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort