apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpm
  labels:
    group: nginx-env
spec:
  replicas: 2
  selector:
    matchLabels:
      workload.es.io: deployment.nginx
  template:
    metadata:
      labels:
        workload.es.io: deployment.nginx
        group: nginx-env
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: "1"
        ovn.kubernetes.io/logical_switch: ovn-default
    spec:
      containers:
        - env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  key: VERSION
                  name: nginx-configmap
          image: 'hub.ecns.io/library/nginx:latest'
          name: nginx
      runtimeClassName: rune


