apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: access-type-test
  name: nodeport-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.nodeport-deploy
  template:
    metadata:
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: '1'
        ovn.kubernetes.io/logical_switch: ovn-default
      creationTimestamp: null
      labels:
        workload.es.io: deployment.nodeport-deploy
        group: access-type-test
    spec:
      containers:
        - image: 'hub.ecns.io/library/nginx:latest'
          imagePullPolicy: IfNotPresent
          name: nodeport-deploy
      runtimeClassName: rune
