apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-demo
  labels:
    group: test-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.es.io: deployment.nginx
  template:
    metadata:
      labels:
        workload.es.io: deployment.nginx
        group: test-demo
      annotations:
        io.katacontainers.config.hypervisor.default_vcpus: "1"
        ovn.kubernetes.io/logical_switch: ovn-default
    spec:
      containers:
        - image: 'hub.ecns.io/library/nginx:latest'
          name: nginx
          volumeMounts:
            - mountPath: /data
              name: vol1
        - image: 'tomcat:latest'
          name: tomcat
          volumeMounts:
            - mountPath: /data
              name: vol1
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: my-pvc
      runtimeClassName: rune

